### PR TITLE
Fix Android 13 notifications

### LINKED ISSUE #147: No notifications are shown
Android 13 requires a new permission before notifications are shown. This permission must be requested by Prepaid Balance.

### PR DESCRIPTION
**Pull request by DrMaxNix**
### This PR implements notification permissions for Android 13 (API 33) and fixes #147

It adds a new string called `notification_permission_denied` which has yet to be translated.

### CODE REVIEW

File: app/src/main/java/com/github/muellerma/prepaidbalance/ui/MainActivity.kt [hunk 1]
```diff
@@ -42,11 +41,23 @@ class MainActivity : AbstractBaseActivity(), SwipeRefreshLayout.OnRefreshListene
         ActivityResultContracts.RequestMultiplePermissions()
     ) { isGranted: Map<String, Boolean> ->
         if (isGranted.all { it.value }) {
-            binding.swiperefresh.isRefreshing = true
-            setDefaultSubscriptionId()
-            onRefresh()
+            // phone permissions granted
+            if(isGranted.containsKey("android.permission.CALL_PHONE") || isGranted.containsKey("android.permission.READ_PHONE_STATE")){
```
Comment (mueller-ma) [inline app/src/main/java/com/github/muellerma/prepaidbalance/ui/MainActivity.kt:45]: You can use a constant instead of a string here and below: `isGranted.containsKey(android.Manifest.permission.CALL_PHONE)`

File: app/src/main/java/com/github/muellerma/prepaidbalance/ui/MainActivity.kt [hunk 2]
```diff
@@ -42,11 +41,23 @@ class MainActivity : AbstractBaseActivity(), SwipeRefreshLayout.OnRefreshListene
...
-            showSnackbar(R.string.permissions_required)
+            // notification permission denied
+            if(isGranted.containsKey(POST_NOTIFICATIONS)){
+                showSnackbar(R.string.notification_permission_denied)
+            }
+
+            // phone permissions denied
+            if(isGranted.containsKey(CALL_PHONE) || isGranted.containsKey(READ_PHONE_STATE)){
+                showSnackbar(R.string.permissions_required)
+            }
```
Comment (mueller-ma) [inline app/src/main/java/com/github/muellerma/prepaidbalance/ui/MainActivity.kt:60]: I'd prefer something like this:

```suggestion
           val message = when {
             isGranted.containsKey(POST_NOTIFICATIONS) -> R.string.notification_permission_denied
             ....
             else -> // throw AssertionError
             }
          showSnackbar(message )   
```

Comment (DrMaxNix) [reply app/src/main/java/com/github/muellerma/prepaidbalance/ui/MainActivity.kt]: resolved by latest commit

**Comment by mueller-ma** [comment]
It may take a bit of time until I review this. Overall looks good!

**Review by mueller-ma — APPROVED** [review]
Thanks!

For the future: Please make sure you don't work on your `main` as that name conflicts locally with the original `main` branch.
