### PR TITLE
Sim card selection to proceed with ussd code request

### LINKED ISSUE #124: Select sim card for ussd code
De app chooses the wrong SIM card for checking the prepaid Balance using the ussd code.

**To Reproduce**
Install the app and enter the ussd code that is needed to check the prepaid Balance.
If there are two SIM cards the app will give an error when reading the prepaid Balance is triggered 
If I remove the SIM card that is not supported with USSD than the app will choose the right SIM card. If I enter the Second SIM card again then the app chooses the wrong SIM card again.

**Expected behavior**
I would like that we app gives you a choice for the sim card to use the ussd code with.

**Screenshots**
I don't have a screenshot.

**Device (please complete the following information):**
 - Device: Nokia X10
 - Android version: 12
 - MCC and MNC (Shown in settings): 
 - MCC: 204
 - MNC: 16 should be 8

**Additional context**
I tried to install the app with only the right SIM card in the phone. That works until I put the second SIM card in the phone again.

### PR DESCRIPTION
**Pull request by Devendra34**
### Fixes #124 
Previouly on swipe behaviour, the app use to directly request USSD without having any user selection for a sim card.
In this PR, the user can see a dialog box from which a sim card can be chosen to proceed the request.
The sim card names shown to the user are directly coming from [SubscriptionInfo](https://developer.android.com/reference/android/telephony/SubscriptionInfo) object's [carrierName](https://developer.android.com/reference/android/telephony/SubscriptionInfo#getCarrierName()) method.

For convenience, if the device has only one sim card in it, then it does not show any list in a dialog, and the flow for the request is same as before.

IMG_20221002_2339421

### CODE REVIEW

**Comment by mueller-ma** [comment]
Instead I'd add a dropdown preference where you can select the SIM card. If the selected sim card isn't present (anymore), there should be an error (add `CheckResult.SimMissing`).

The default value for this setting should be the primary sim card.

**Comment by Devendra34** [comment]
Hi @mueller-ma, the defa

**Comment by Devendra34** [comment]
Hi @mueller-ma, 
Like I mentioned before, the user won't get any popup, if there is only 1 sim. Else he has such alert dialog using setItems() method to choose one.

**Comment by Devendra34** [comment]
If you don't like this selection of using setItems() in alert dialog, we can go ahead with radio buttons list provided by alert dialog

**Comment by mueller-ma** [comment]
I don't like the idea of the alert dialog at all. At least for me I don't use the pull-to-refresh at all and let the app fetch the balance in background automatically.

**Comment by Devendra34** [comment]
So let's do one thing, in the preference screen we can have one option to choose a sim card from drop down. And let's remove everything that we had in main activity. 
Sounds good?

**Comment by mueller-ma** [comment]
Yes, sounds good.

**Comment by Devendra34** [comment]
@mueller-ma,
I see that we are using [Preference](https://developer.android.com/reference/androidx/preference/Preference) API for that settings screen. The closest class that we can use in our use-case is [ListPreference](https://developer.android.com/reference/androidx/preference/ListPreference) that gives us radio based options kind of UI. So the change would be instead of drop down we have radio based option list from android. But the functionality reaminas for keeping default option remains same as discussed.

**Comment by Devendra34** [comment]
I'm pushing with the above discussed changes.
Here is the new screenshot
IMG_20221003_033251 (1)

**Comment by Devendra34** [comment]
Hi @mueller-ma, have you seen the above changes?

**Comment by mueller-ma** [comment]
Overall looks good, but I haven't reviewed it in detail yet.

**Comment by Devendra34** [comment]
Hey @mueller-ma, 
Let me know if there is any issue in the review. 
Waiting for your feedback. 
Thank!

File: app/src/main/java/com/github/muellerma/prepaidbalance/work/CheckBalanceWorker.kt [hunk 1]
```diff
@@ -155,8 +156,13 @@ class CheckBalanceWorker(
                 return callback(CheckResult.USSD_INVALID, null)
             }
 
+            val subscriptionId = context.prefs().getString("subscription_id", "")
+                .orEmpty().toIntOrNull() ?: return callback(CheckResult.SUBSCRIPTION_INVALID, null)
```
Comment (mueller-ma) [inline app/src/main/java/com/github/muellerma/prepaidbalance/work/CheckBalanceWorker.kt:160]: Can you handle `subscriptionId  == null` as "use default sim card", so don't call `createForSubscriptionId()` below. Then you can remove `setDefaultSubscriptionId()` and maybe also remove `CheckResult.SUBSCRIPTION_INVALID`.

Comment (Devendra34) [reply app/src/main/java/com/github/muellerma/prepaidbalance/work/CheckBalanceWorker.kt:160]: @mueller-ma, if you don't use `createForSubscriptionId()`, then while using 2 sim cards, you will get same error as before.
This PR was intended to fix that error. So I think we can't ignore  `createForSubscriptionId()`.
What else do you propose while keeping this limitation?

Comment (mueller-ma) [reply app/src/main/java/com/github/muellerma/prepaidbalance/work/CheckBalanceWorker.kt:160]: I want to ensure that there's no error for people with one sim card. If a user has multiple sim cards, he can set the correct one in the settings.

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -18,7 +18,10 @@
     <string name="channel_name_balance_increased">Balance increased</string>
     <string name="channel_name_threshold_reached">Threshold reached</string>
     <string name="invalid_ussd_code">Invalid USSD code entered</string>
+    <string name="invalid_subscription">Invalid Subscription, check default</string>
```
Comment (mueller-ma) [inline app/src/main/res/values/strings.xml:21]:
```suggestion
    <string name="invalid_subscription">Invalid sim card selected, check settings</string>
```

File: app/src/main/res/values/strings.xml [hunk 3]
```diff
@@ -18,7 +18,10 @@
...
     <string name="ussd_code">USSD code</string>
+    <string name="subscription_id">Subscription</string>
```
Comment (mueller-ma) [inline app/src/main/res/values/strings.xml:23]:
```suggestion
    <string name="subscription_id">Sim card</string>
```

File: app/src/main/res/values/strings.xml [hunk 4]
```diff
@@ -18,7 +18,10 @@
...
+    <string name="subscription_summary">Change default sim card</string>
```
Comment (mueller-ma) [inline app/src/main/res/values/strings.xml:24]: This string doesn't seem to be used.

File: app/src/main/java/com/github/muellerma/prepaidbalance/ui/PreferenceActivity.kt [hunk 5]
```diff
@@ -68,6 +73,22 @@ class PreferenceActivity : AppCompatActivity() {
...
+                ) == PackageManager.PERMISSION_GRANTED) {
+
+                val subscriptionManager = requireContext().getSystemService(SubscriptionManager::class.java)
+                val (subscriptionIds, carrierNames) = subscriptionManager.activeSubscriptionInfoList.let { subscriptions ->
+                    val subscriptionIds = subscriptions.map { "${it.subscriptionId}" }.toTypedArray()
+                    val carrierNames = subscriptions.map { it.carrierName }.toTypedArray()
+                    subscriptionIds to carrierNames
+                }
+
+                val subscriptionIdPref: ListPreference = getPreference("subscription_id") as ListPreference
```
Comment (mueller-ma) [inline app/src/main/java/com/github/muellerma/prepaidbalance/ui/PreferenceActivity.kt:87]:
```suggestion
                val subscriptionIdPref = getPreference("subscription_id") as ListPreference
```

**Review by mueller-ma — CHANGES_REQUESTED** [review]
Can you rebase (not merge) this branch on main?

File: app/src/main/res/values/strings.xml (hunk 4 above)
Comment (Devendra34) [reply app/src/main/res/values/strings.xml:24]: I'll use it as description for subscription preference.

**Comment by Devendra34** [comment]
> Can you rebase (not merge) this branch on main?

Hi @mueller-ma, I have adopted your suggested changes from your code review.
The branch has no conflicts for the merge, do we still need a rebase here?
If not, then kindly update your review

**Comment by Devendra34** [comment]
Hi @mueller-ma,
Let me know if there is anything left from my end.
Looking forward for your updated review.
Thanks!

File: app/src/main/java/com/github/muellerma/prepaidbalance/ui/PreferenceActivity.kt [hunk 6]
```diff
@@ -68,6 +73,22 @@ class PreferenceActivity : AppCompatActivity() {
                 }
             }
 
+            if (ActivityCompat.checkSelfPermission(requireContext(),
+                    Manifest.permission.READ_PHONE_STATE
+                ) == PackageManager.PERMISSION_GRANTED) {
```
Comment (mueller-ma) [inline app/src/main/java/com/github/muellerma/prepaidbalance/ui/PreferenceActivity.kt:78]: If not granted, ask for permissions and disable setting.

**Review by mueller-ma — CHANGES_REQUESTED** [review]
App crashes when I try to open the ListPreference:

````
java.lang.IllegalStateException: ListPreference requires an entries array and an entryValues array.
	at androidx.preference.ListPreferenceDialogFragmentCompat.onCreate(ListPreferenceDialogFragmentCompat.java:55)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
````

File: app/src/main/java/com/github/muellerma/prepaidbalance/ui/PreferenceActivity.kt (hunk 6 above)
Comment (Devendra34) [reply app/src/main/java/com/github/muellerma/prepaidbalance/ui/PreferenceActivity.kt]: > If not granted, ask for permissions and disable setting.

@mueller-ma ,
Made this change. Please update the review

**Comment by mueller-ma** [comment]
Can you allow me to push to your branch? I'll push to commits then and then it should be ready to merge.

**Comment by mueller-ma** [comment]
There should be a checkbox to grant me permissions for this branch only: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by mueller-ma** [comment]
I pushed my commits. Can you do a quick review?

**Comment by Devendra34** [comment]
> I pushed my commits. Can you do a quick review?

Looks good to me! Nice!
